<?xml version="1.0"?>
<package format="3">
  <name>vio_node</name>
  <version>0.0.0</version>
  <description>Learning-focused stereo visual-inertial odometry node</description>
  <maintainer email="pmkohler@gmail.com">peter</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclcpp</depend>
  <depend>ament_cmake_auto</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>message_filters</depend>
  <depend>eigen3_cmake_module</depend>
  <depend>eigen</depend>
  <depend>opencv</depend>
  <depend>cv_bridge</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rosbag2_py</exec_depend>
  <exec_depend>rosidl_runtime_py</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
