<?xml version="1.0"?>
<package format="3">
  <name>noisy_imu</name>
  <version>0.0.0</version>
  <description>Publishes IMU with added white noise</description>
  <maintainer email="pmkohler@gmail.com">peter</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>ament_cmake_auto</depend>
  <depend>sensor_msgs</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>


