vio_node:
  ros__parameters:
    imu_sub_topic_name: "/chassis/imu"
    left_img_sub_topic_name: "/front_stereo_camera/left/image_raw"
    left_camera_info_sub_topic_name: "/front_stereo_camera/left/camera_info"
    right_img_sub_topic_name: "/front_stereo_camera/right/image_raw"
    right_camera_info_sub_topic_name: "/front_stereo_camera/right/camera_info"
    vio_pub_topic_name: "/vio/odom"
    publish_debug_stereo_features: true
    world_frame_id: "vio_odom"
    body_frame_id: "base_link"
    imu_frame_id: "chassis_imu"
    left_camera_frame_id: "front_stereo_camera_left_rgb"
    right_camera_frame_id: "front_stereo_camera_right_rgb"
    publish_tf: false
    camera_imu_time_offset_sec: 0.0
    imu_msg_gap_threshold_s: 0.05
    imu_msg_buffer_window_s: 10.0
    imu_initialization_window_s: 2.0
    imu_initialization_min_samples: 100
    imu_stationary_max_gyro_mean_norm_rad_s: 0.005
    imu_stationary_max_gyro_stddev_rad_s: 0.001
    imu_stationary_max_accel_stddev_m_s2: 0.01
    imu_stationary_gravity_magnitude_m_s2: 9.8
    imu_stationary_gravity_tolerance_m_s2: 0.1
